name: Generate APAC MP4 File

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-generate:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up specific Xcode version
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.1' # Use Xcode 16.1.0, the closest available version to 16.0

    # Verify Xcode and clang version
    - name: Verify Xcode and clang version
      run: |
        xcodebuild -version
        clang++ --version
        xcrun --sdk iphoneos --show-sdk-path

    # Debug: List files in repository
    - name: Debug directory contents
      run: ls -R apple-positional-audio-codec-invalid-header-main

    # Create build script
    - name: Create build script
      working-directory: apple-positional-audio-codec-invalid-header-main
      run: |
        cat << 'EOF' > build_encodeme.sh
        #!/bin/bash
        set -e
        clang++ -g -Os -std=c++2b -fmodules -fcxx-modules -fobjc-arc -arch arm64 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -framework AVFAudio -framework AudioToolbox encodeme.mm -o encodeme
        chmod +x encodeme
        EOF
        chmod +x build_encodeme.sh

    # Compile encodeme.mm
    - name: Compile encodeme.mm
      working-directory: apple-positional-audio-codec-invalid-header-main
      run: ./build_encodeme.sh

    # Debug: Verify simulator availability
    - name: Debug simulator availability
      run: xcrun simctl list devices

    # Boot iOS simulator
    - name: Boot iOS simulator
      run: |
        xcrun simctl boot "iPhone 15" || true # Ignore if already booted
        xcrun simctl status_bar "iPhone 15" override --time "2025-05-29T15:00:00-0700" --batteryState charged --batteryLevel 100

    # Run the binary in simulator
    - name: Run encodeme
      working-directory: apple-positional-audio-codec-invalid-header-main
      run: xcrun simctl spawn "iPhone 15" ./encodeme

    # Verify generated file
    - name: List generated file
      working-directory: apple-positional-audio-codec-invalid-header-main
      run: ls -lh sound.m4a || echo "No sound.m4a file found"

    # Upload MP4 file as artifact
    - name: Upload MP4 artifact
      uses: actions/upload-artifact@v4
      with:
        name: apac-mp4-file
        path: apple-positional-audio-codec-invalid-header-main/sound.m4a
        retention-days: 7
        if-no-files-found: warn
