name: Upload AudioCodecs Component

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  upload:
    name: Upload AudioCodecs Artifact
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Copy AudioCodecs.component (requires sudo, but GitHub-hosted runners may have restrictions)
      - name: Copy AudioCodecs Component
        run: |
          SOURCE="/System/Library/Components/AudioCodecs.component"
          DEST_DIR="./audiocodecs_backup"
          ZIP_FILE="./audiocodecs_backup/AudioCodecs_component.zip"
          
          mkdir -p "$DEST_DIR"
          
          if [ ! -d "$SOURCE" ]; then
            echo "Error: AudioCodecs.component not found at $SOURCE"
            exit 1
          fi
          
          # Attempt to copy (may fail due to SIP or permissions on GitHub runner)
          sudo cp -R "$SOURCE" "$DEST_DIR"
          
          if [ $? -ne 0 ]; then
            echo "Error: Failed to copy AudioCodecs.component. Uploading pre-copied file instead."
            exit 1
          fi
          
          # Compress the file
          cd "$DEST_DIR"
          zip -r "$ZIP_FILE" "AudioCodecs.component"
          
          # Clean up
          rm -rf "$DEST_DIR/AudioCodecs.component"

      # Upload the artifact
      - name: Upload AudioCodecs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioCodecs-component
          path: ./audiocodecs_backup/AudioCodecs_component.zip
          if-no-files-found: error
